/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "led.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	LedInit(LED_BLUE);
	LedInit(LED_GREEN);
	LedInit(LED_RED);
	LedInit(LED_ORANGE);

	TimerInit();
	while(1) {
		LedOn(LED_BLUE);
		//TimerDelayMs(700);
		LedOn(LED_GREEN);
				//TimerDelayMs(700);
				LedOn(LED_RED);
						//TimerDelayMs(700);
						LedOn(LED_ORANGE);
			TimerDelayMs(3000);
			LedOff(LED_BLUE);
				//TimerDelayMs(700);
				LedOff(LED_GREEN);
						//TimerDelayMs(700);
						LedOff(LED_RED);
								//TimerDelayMs(700);
								LedOff(LED_ORANGE);
					TimerDelayMs(7000);


	/*SystemInit();
		DelayMs(1);
		LedInit(LED_GREEN);
		LedInit(LED_ORANGE);
		LedInit(LED_RED);
		LedInit(LED_BLUE);
		TimerInit();
		while(1) {
			LedON(LED_GREEN);
			LedON(LED_ORANGE);
			LedON(LED_RED);
			LedON(LED_BLUE);
			TimerDelaysMs(700);
	*/
}return 0;
}


